### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-admin#122]
Pre-commit hooks should be added, documented and applied as we did in all our python repositories.
Pre-commit hooks are to be added by `pre-commit` app: https://pre-commit.com/
See those pull requests for reference: bitcartcc/bitcart#238, bitcartcc/bitcart-sdk#32, bitcartcc/bitccl#13

Of course, python-related tasks should be removed, and a set of rules for js repos should be created. Pre-commit checks should run most basic checks for file consistency (newlines, trailing whitespaces, etc), also probably eslint with our config (so that it runs prettier too) and any other useful checks for js code

We currently use husky for pre-commit hooks. Preferably pre-commit would also run the linting run by husky, or just run husky itself

The main issue is to make pre-commit use versions from package.json without manually specifying them in it's config file

**Important**: the pull request will be merged without squash, so please try to make it like reference PRs, first commit adding the pre-commit config, and in next commits applying fixers one by one, and in last commits documenting it and adding to CI. To add to CI you can use bitcartcc/lint action by our bitcartcc/bitcartcc-shared orb. See other pull requests for reference

**Comment by hmajid2301** [comment]
I can pick this up as well seeing as im doing, https://github.com/bitcartcc/bitcart-blog/issues/110

**Comment by MrNaif2018** [comment]
Alright, our js repos will share same config anyway.
See [this comment](https://github.com/bitcartcc/bitcart-store/issues/316#issuecomment-932450528) for how to get api running for admin panel
Do you have any questions so far regarding pre-commit setup?

**Comment by hmajid2301** [comment]
Wait do you want to use the same `pre-commit` library as you use in Python. Or can I just simply setup pre-commit checks using Husky ?

**Comment by MrNaif2018** [comment]
The same pre-commit library as in python. It is installed via numerous ways, one of which is via python, and it can run git hooks in any language. It can run prettier, eslint, some misc formatters and so on without requiring user to manually install them

**Comment by hmajid2301** [comment]
Ok sure I guess we assume the user already has it installed ? or shall I update the README with say how to do it via curl ?

**Comment by MrNaif2018** [comment]
For js repos we can't assume user has python installed, so yes, installing via curl method should be documented (and a link to pre-commit install docs showing all methods)

**Comment by hmajid2301** [comment]
alright cool, I can do that!
