### ISSUE TITLE
Set up formatting guidelines

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-admin#13]
Currently, we don't have any formatting set up (I format code with vscode eslint extension, but it isn't a formatter actually).
We should create something like https://github.com/bitcartcc/bitcart/blob/master/CODING_STANDARDS.md#formatting, but for vue repos.
What are the choices available? Prettier, for example?
Last time I used it, it was formatting files in a weird way, but it's probably opinionated.
Ideally our formatter we'll use should be like black in python - https://github.com/psf/black - almost no configuration, but sensible, good for readability choices.
We'll need the formatter we choose to be able to check if files are formatted correctly - we need it as a part of our CI process.
P.S. @orestischaral you may want to take a look at it

**Comment by TobyAsE** [comment]
See [here](https://nuxtjs.org/guide/development-tools/#eslint-and-prettier)

**Comment by MrNaif2018** [comment]
Done, see https://github.com/bitcartcc/bitcart/blob/master/CODING_STANDARDS.md#coding-guidelines-for-vuejavascript-code
